version: '3'
services:
  web:
    environment:
      MONGO_URL: "mongodb://mongo:27017/notification-service"
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
  mongo:
    image: "mongo:3.4"